version: '3.8'

services:
  postgres:
    image: postgres:14.15-alpine3.21
    container_name: finop_postgres
    environment:
      POSTGRES_USER: finop
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: finop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres_test:
    image: postgres:14.15-alpine3.21
    container_name: finop_postgres_test
    environment:
      POSTGRES_USER: finop_test
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: finop_test
    ports:
      - "5433:5432"
  finop:
    container_name: finop
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env.docker

volumes:
  postgres_data: